// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.2
// source: lib/protos/v1/payment/payment.proto

package payment

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPaymentServiceTransferBalanceService = "/e_wallet_microservices_v2.PaymentService/TransferBalanceService"

type PaymentServiceHTTPServer interface {
	TransferBalanceService(context.Context, *TransferBalanceRequest) (*TransferBalanceResponse, error)
}

func RegisterPaymentServiceHTTPServer(s *http.Server, srv PaymentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/payment/transfer", _PaymentService_TransferBalanceService0_HTTP_Handler(srv))
}

func _PaymentService_TransferBalanceService0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TransferBalanceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceTransferBalanceService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TransferBalanceService(ctx, req.(*TransferBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TransferBalanceResponse)
		return ctx.Result(200, reply)
	}
}

type PaymentServiceHTTPClient interface {
	TransferBalanceService(ctx context.Context, req *TransferBalanceRequest, opts ...http.CallOption) (rsp *TransferBalanceResponse, err error)
}

type PaymentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPaymentServiceHTTPClient(client *http.Client) PaymentServiceHTTPClient {
	return &PaymentServiceHTTPClientImpl{client}
}

func (c *PaymentServiceHTTPClientImpl) TransferBalanceService(ctx context.Context, in *TransferBalanceRequest, opts ...http.CallOption) (*TransferBalanceResponse, error) {
	var out TransferBalanceResponse
	pattern := "/v1/payment/transfer"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentServiceTransferBalanceService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
